global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'legal-docs-app'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Changed from 'app:3000'
    metrics_path: '/metrics'
    scrape_interval: 5s
